# path
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

# Homebrew
ls -A /Library/Developer/CommandLineTools/usr/bin &>/dev/null || xcode-select --install
type /opt/homebrew/bin/brew &>/dev/null && eval "$(/opt/homebrew/bin/brew shellenv)"

# Java
[ -d "$(brew --prefix openjdk)/bin" ] && PATH="$(brew --prefix openjdk)/bin:$PATH"
type /usr/libexec/java_home &>/dev/null && export JAVA_HOME="$(/usr/libexec/java_home)"

# Flutter
type ghq &>/dev/null && [ -d "$(ghq root)/github.com/flutter/flutter/bin" ] &&
  PATH="$(ghq root)/github.com/flutter/flutter/bin:$PATH"

# Android SDK
if [ -d "$HOME/Library/Android/sdk" ]; then
  export ANDROID_HOME="$HOME/Library/Android/sdk"
  PATH="$ANDROID_HOME/emulator:$PATH"
  PATH="$ANDROID_HOME/tools:$PATH"
  PATH="$ANDROID_HOME/tools/bin:$PATH"
  PATH="$ANDROID_HOME/platform-tools:$PATH"
fi

# Pipenv
export PIPENV_VENV_IN_PROJECT=1
export PIPENV_IGNORE_VIRTUALENVS=1

# Poetry
[ -d "$HOME/.poetry/bin" ] && PATH="$HOME/.poetry/bin:$PATH"
export POETRY_VIRTUALENVS_IN_PROJECT=true

# Python
[ -d "$(brew --prefix python)/libexec/bin" ] && PATH="$(brew --prefix python)/libexec/bin:$PATH"

# asdf
export ASDF_DATA_DIR="$HOME/.asdf"
PATH="$ASDF_DATA_DIR/shims:$(brew --prefix asdf)/bin:$PATH"

# Flutter
if type asdf &>/dev/null && asdf where flutter &>/dev/null; then
  export FLUTTER_ROOT="$(asdf where flutter)"
fi

# Yarn
if type yarn &>/dev/null; then
  yarn_global_path="$(yarn global bin)"
  [[ ":$PATH:" != *"$yarn_global_path"* ]] && PATH="$yarn_global_path:$PATH"
  unset yarn_global_path
fi

if [ -n "$BASH_VERSION" ]; then
  if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi
