export LANG=ja_JP.UTF-8

autoload -Uz colors
colors

setopt no_beep
setopt nolistbeep

setopt correct
setopt print_eight_bit

# history
HISTFILE="$HOME/.zsh_history"
HISTSIZE=1000
SAVEHIST=100000

setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt share_history

# enable zsh completions
if type brew &>/dev/null; then
  if [ -d "$(brew --prefix)/share/zsh-completions" ]; then
    FPATH="$(brew --prefix)/share/zsh-completions:$FPATH"
  fi
  if [ -f "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
    source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
  fi
  if [ -f "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
    source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  fi
fi

# complement
autoload -Uz compinit
compinit

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# aliases
if type dircolors &>/dev/null; then
  [ -r ~/.dircolors ] && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi
if type gdircolors &>/dev/null; then
  [ -r ~/.dircolors ] && eval "$(gdircolors -b ~/.dircolors)" || eval "$(gdircolors -b)"
  alias ls='gls --color=auto'
  alias dir='gdir --color=auto'
  alias vdir='gvdir --color=auto'
fi

# functions
# fuzzy finder
f() {
  case $1 in
    'git')
      local repository_name="$(ghq list | fzf --layout=reverse --preview="ls -a $(ghq root)/{}")"
      [ -n "$repository_name" ] && cd "$(ghq root)/$repository_name"
      ;;
    'ssh')
      local host_name="$(grep -Ei '^Host\s+.+' $HOME/.ssh/config | grep -Ev '[*?]' | awk '{print $2}' | sort | fzf --layout=reverse --preview="grep -A 61 -B 2 --color=always {} $HOME/.ssh/config")"
      [ -n "$host_name" ] && echo "> ssh $host_name" && ssh "$host_name"
      ;;
    *)
      echo 'Usage: f [command]'
      echo 'Commands:'
      echo '  git  Open a git repository.'
      echo '  ssh  Login to a remote machine.'
      ;;
  esac
}
